### ISSUE TITLE
Vortice XAudio2 causing exception on latest Windows

### ISSUE THREAD

**Issue by mrcoffeeee** [amerkoleci/Vortice.Windows#122]
I want to use XAudio2 for a NET project but as soon as I initiate the IXAudio device an exception is thrown saying that my platform is not supported. I use the latest Windows 10 updates (release) and Visual Studio 2019 with NET 4.7.2. See the attached image.

1. Create a NET console or Winforms project
2. Add Vortice XAudio2 from Nuget
3. Create an IXAudio device
4. Run the code

**Expected behavior**
Program should start without any exception

**Screenshots**
![VorticeXAudioException](https://user-images.githubusercontent.com/28219296/108813871-190f6580-75b2-11eb-9142-17b3b1026080.png)

**Desktop:**
 - OS: Windows 10 20H2 Build: 19042.844

**Sample Code:**

`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Vortice.XAudio2;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var XTEST = new IXAudio2(ProcessorSpecifier.DefaultProcessor);
            Console.ReadKey();
        }
    }
}

`

**Comment by amerkoleci** [comment]
It works well for me, new console application targeting net5.

**Comment by manuelxmarquez** [comment]
I just ran into the same error. I got the exception:

```
System.TypeInitializationException: The type initializer for 'Vortice.XAudio2.XAudio2Native' threw an exception.
System.PlatformNotSupportedException: Cannot load native libraries on this platform: Microsoft Windows 10.0.18363 
   at Vortice.XAudio2.XAudio2Native.LoadXAudio2()
   at Vortice.XAudio2.XAudio2Native..cctor()
   --- End of inner exception stack trace ---
   at Vortice.XAudio2.XAudio2Native.XAudio2Create(Int32 flags, ProcessorSpecifier processorSpecifier)
   at Vortice.XAudio2.XAudio2.XAudio2Create(ProcessorSpecifier processorSpecifier, Boolean registerCallback)
```

It seems the native assemblies are not being copied to the output folder properly. I dug around the code and found that there is a _targets_ file being added to the NuGet package but it doesn't work, probably because it is in the wrong location. Also, it is not in the multi targeting folder either. It did work for one target framework but not net472.

I made a change and tested on my local machine and seemed to fix the issue. I will submit a pull request now with what worked for me. Here is what my modified package looks like:

![image](https://user-images.githubusercontent.com/30425852/111017386-38afd780-8381-11eb-858b-49dc55a2884c.png)

In the meantime, you can copy the missing DLLs from the package folder to your output bin folder. It should look something like this:
```
bin\Debug\net472\x64\xaudio2_9redist.dll
bin\Debug\net472\x86\xaudio2_9redist.dll
```

Your package folder is probably located in `C:\Users\[USER]\.nuget\packages\vortice.xaudio2\1.9.7-beta\runtimes\win-x[86 or 64]\native`

BTW, thanks for creating this project! I managed to switch my entire game engine from SharpDX to Vortice in under 2 days.

**Comment by amerkoleci** [comment]
Thanks for kind words and PR, feel free to share screenshots or something else of your game engine in discussions

**Comment by mrcoffeeee** [comment]
Hello, sorry i hadn´t much time to respond quickly enough. Using Netcore 3 or NET5 solved this issue for me. I ported the app to NET5 but I am still wondering as the last legacy NET (4.7, 4.8) versions should also fit into the NET2 standard.

**Comment by mrcoffeeee** [comment]
but i ran into another issue thats probably something new. I managed to use the reverb with the reverb presets but somehow some of them work (like the "Default") and some not (like the "Arena")

`var xaudio2 = new IXAudio2(ProcessorSpecifier.DefaultProcessor);
            var mv = xaudio2.CreateMasteringVoice(1, 48000);

            var reader = new NAudio.Wave.WaveFileReader("TEST.wav");
            var array = new byte[reader.Length];
            reader.Read(array, 0, array.Length);
            var targetBuffer = new AudioBuffer(array, BufferFlags.None);
            int encoding = (int)reader.WaveFormat.Encoding;

            var waveFormat = WaveFormat.CreateCustomFormat((WaveFormatEncoding)encoding,
                reader.WaveFormat.SampleRate,
                reader.WaveFormat.Channels,
                reader.WaveFormat.AverageBytesPerSecond,
                reader.WaveFormat.BlockAlign,
                reader.WaveFormat.BitsPerSample);

            targetBuffer.LoopCount = IXAudio2.LoopInfinite;
            var reverb = Vortice.XAudio2.Fx.Fx.CreateAudioReverb();
            var revpar = Vortice.XAudio2.Fx.Presets.Default;
            // var revpar = Vortice.XAudio2.Fx.Presets.Default; --> doesnt work

            mv.SetVolume(.9f);
            var sourceVoice = xaudio2.CreateSourceVoice(waveFormat);
            var ef = new EffectDescriptor(reverb,1);
            sourceVoice.SetEffectChain(ef);
            sourceVoice.SetEffectParameters(0, Vortice.XAudio2.Fx.Fx.ReverbConvertI3DL2ToNative(revpar, true));
            sourceVoice.SubmitSourceBuffer(targetBuffer);
            sourceVoice.Start();
            Console.WriteLine("Vortice XAudio2 Playing ...");
            Console.ReadKey();`

Here the attached test.wav file:

[TEST.zip](https://github.com/amerkoleci/Vortice.Windows/files/6134554/TEST.zip)

**Comment by manuelxmarquez** [comment]
I had a multi targeting project and it worked for .NET Core but not the legacy framework. I think it is because the newer frameworks recognize the special runtimes folder in the NuGet package but not legacy frameworks.

I also just checked and tested that the target is not needed in the buildMultiTargeting folder and submitted a PR to keep the code clean.

I have no idea about your reverb issue, sorry. I will try to check later, maybe I will expand the sample projects for people to easily get a reference.

**Comment by mrcoffeeee** [comment]
thanks for checking :) i played around with reverb values and it seems that changing parameters does not have any effect. I built the same xaudio2 setup on c++ and it works. It might be that the default parameters never get changed or am I doing something fundamentally wrong?

`var revpar = new Vortice.XAudio2.Fx.ReverbParameters
            {
                WetDryMix = 100,
                RoomFilterFreq = 5000,
                ReverbGain = 20,
                ReverbDelay = 85,
                RoomSize = 100f,
                DecayTime = 5000,
                LowEQCutoff = 9
            };
            sourceVoice.SetEffectParameters(0, revpar);`

**Comment by amerkoleci** [comment]
Can you open new issue please so we can track independently?
