### ISSUE TITLE
Multiplatform support

### ISSUE THREAD

**Issue by amerkoleci** [amerkoleci/Vortice.Windows#20]
Will add support for **net461** and **uap10.0.16299** using https://github.com/onovotny/MSBuildSdkExtras.
In this way we can have per platform code and Add/Remove methods not supported in UAP in order to avoid certification issues when deploying to store.

CC: @Aminator  and @Sergio0694 if you have any thoughts about this?

**Comment by Aminator** [comment]
I don't really deem it necessary especially .NET Core on desktop and UWP will become the same in the future. If you want to use WinRT APIs, I would suggest the [Microsoft.Windows.SDK.Contracts](https://www.nuget.org/packages/Microsoft.Windows.SDK.Contracts) NuGet package.

**Comment by amerkoleci** [comment]
I see, but there are some other differences, for example when creating ComObject, in desktop environment you use CoCreateInstance while in UWP you CoCreateInstanceFromApp, also the XInput logic and Direct2D1 can include the correct implementation.

**Comment by Sergio0694** [comment]
I'm afraid I'm not able to add much to the conversation, other than a few observations:
1) I agree with @Aminator that UWP and .NET Core will basically become the same, as UWP will be switching to .NET Core 3.0 (and then .NET 5) in the coming months/years
2) I mean, as long as doing this doesn't break anything, I won't complain 😄
3) Personally I'm not particularly interested in net461, as for some reason my lib doesn't work there due to some weird behavior of ILSpy on that framework (that's why I locked that out by upgrading to .NET Standard 2.1)

**Comment by amerkoleci** [comment]
I see, thanks for reply.

Lot of directx header has the window app partition defined in native side, which is desktop or something else when compiling to UWP, probably removing API not allowed in UWP makes sense.

Won't break nothing just it will generate 3 assemblies per project

**Comment by Aminator** [comment]
But you will keep a .NET Standard version, right? Because in my game engine I only reference Vortice packages in .NET Standard projects.

**Comment by amerkoleci** [comment]
Of couse yes, the idea is to have netstandard2.0, net461 and uap target frameworks.

**Comment by amerkoleci** [comment]
Closed, latest trunk maps compilation per platform and handle differences
